db:
  host: localhost
  port: 5432
  database: starbux
  connection-params: autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  username: postgres
  password: YourStrongPassw0rd

spring:
  jpa:
    show-sql: true

HOSTNAME: leader